### ISSUE TITLE
左侧主题切换

### ISSUE THREAD

**Issue by jifeilong9** [yixiangling/abp-ng-Zorro#3]
https://cipchk.github.io/ng-alain/dashboard/v1
![image](https://user-images.githubusercontent.com/24316291/37691677-7b5d4460-2cee-11e8-9561-10885f0d828c.png)
大佬这个项目左侧主题可以切换，您看可以搞过来吧

**Comment by yixiangling** [comment]
ng-alain左侧的导航是自己实现的一套，并非使用的ng-zorro的menu。现在我使用的是ng-zorro的menu在更换左侧导航主题时样式会出现不匹配问题，所以现在并未进行调整。已经计划迁移ng-alain的导航，现在等待ng-zorro 的0.7正式版发布后进行全部更新

**Comment by yixiangling** [comment]
已处理导航菜单深色主题
