### ISSUE TITLE
为毛弹窗带闪光？

### ISSUE THREAD

**Issue by laosandegudai** [yixiangling/abp-ng-Zorro#5]
弹窗怎么总是闪一下？

**Comment by yixiangling** [comment]
model的html里的*ngIf="modalVisible"去掉就没问题。

示例代码里的逻辑是等待异步数据加载完成后显示元素，但因为model已经弹出了所以看起来会闪一下

**Comment by laosandegudai** [comment]
试了下不行啊。

**Comment by yixiangling** [comment]
abp-ng-Zorro/src/app/pages/users/edit-user/edit-user.component.html
相关示例代码已修改，可以拉取新代码后看看写法

**Comment by laosandegudai** [comment]
大佬，可以了。
